name: Build
on:
  push:
    branches:
      - master
      - tm/v2
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

defaults:
  run:
    working-directory: go/src/github.com/tommartensen/jaga

jobs:
  build-cli:
    name: Build CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          path: go/src/github.com/tommartensen/jaga
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Generate proto gRPC code
        run: |
          pwd
          ls -lisa
          make proto-install proto-generate
      - name: Build CLI
        run: |
          make build-cli
      - name: Test CLI
        run: |
          ${{ github.workspace }}/build/jagactl --version
