name: Build
on:
  push:
    branches:
      - master
      - tm/v2
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build-cli:
    name: Build CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} # TODO: support branch/master
          fetch-depth: 0
      - name: Generate proto gRPC code
        run: |
          make proto-install proto-generate
      - name: Build CLI
        run: |
          make build-cli
      - name: Test CLI
        run: |
          ${{ github.workspace }}/build/jagactl --version
